### ISSUE TITLE
Full VQA-X dataset

### ISSUE THREAD

**Issue by anshumanvenkatesh** [Seth-Park/MultimodalExplanations#8]
The VQA-X google drive location contains 1000 images from val and test each. Is there any way to access the rest of the data?

**Comment by Seth-Park** [comment]
The data in google drive contains only the annotations for textual and visual explanations, meaning that you will have to download the images from the official VQA website (https://visualqa.org/download.html). The 1000 npz files you are seeing are ground-truth annotations for visual pointing. Each file contains 3 heatmaps collected from humans. Due to constraints in resources, we only collected 1000 and evaluated on those.
